"""Find text a human should look at before trusting the extraction.

This is a review aid, not a corrector. Nothing here rewrites a document. Each
finding is a suggestion with the evidence behind it, and a person accepts or
rejects it — the same contract as a spell checker. Automatic "correction" of a
garbled citation is how fabricated citations get made, so candidates are
generated by explicit character substitution only and are never applied.

Three detectors, aimed at the two failure modes actually measured on OCR output:

1. Citation-shaped text that was NOT extracted. A single wrong character in the
   reporter ("30 R3d 197" for "30 P.3d 197") makes eyecite skip the citation
   entirely, with no error. These are silently lost.

2. Party names containing classic OCR confusions. "Coffman" read as "Coffinan",
   "Chavez" as "Cliavez". Extraction reports these with full confidence because
   the reporter matched; only the name is wrong.

3. The same reporter citation appearing with different party names. One spelling
   is wrong and the disagreement itself is the evidence. No vote is taken: on
   one real opinion the wrong spelling outnumbered the right one 11 to 1.
"""

from __future__ import annotations

import re
from dataclasses import asdict, dataclass, field
from typing import Any

from reporters_db import EDITIONS, VARIATIONS_ONLY

# Character sequences Tesseract confuses, as (seen, likely) pairs. Applied in
# both directions to generate candidates.
_CONFUSIONS = (
    ("in", "m"),
    ("rn", "m"),
    ("li", "h"),
    ("cl", "d"),
    ("tl", "d"),
    ("vv", "w"),
    ("ii", "n"),
    ("ri", "n"),
    ("nn", "m"),
)

# Single-character confusions are real but far too common to flag on their own:
# every word containing an "l" would match. They are used only for reporter
# tokens, where the candidate is checked against a closed set.
_CHAR_CONFUSIONS = (
    ("I", "l"),
    ("l", "I"),
    ("0", "O"),
    ("O", "0"),
    ("5", "S"),
    ("S", "5"),
    ("8", "B"),
    ("B", "8"),
    ("1", "l"),
)

# "<volume> <reporter> <page>" shaped text, the skeleton of every case citation.
_CITATION_SHAPE = re.compile(
    r"\b(?P<volume>\d{1,4})\s+"
    r"(?P<reporter>[A-Za-z][A-Za-z0-9.'’ ]{0,18}?)\s+"
    r"(?P<page>\d{1,5})\b"
)

# Rules of procedure/evidence look like citations but are not reporters.
_RULE_MARKER = re.compile(
    r"\b(crim|civ|evid|app|bankr|R)\.?\s*P\.?\b|"
    r"\bR\.\s*(Civ|Crim|Evid|App)",
    re.IGNORECASE,
)

_KNOWN_REPORTERS = set(EDITIONS) | set(VARIATIONS_ONLY)

# "P.3d", "P.3d." and "P3d" all normalise to the same key, so the map is built
# variations first and canonical editions second: a suggestion should offer the
# proper citation form, not a recognised misspelling of it.
_NORMALISED_REPORTERS: dict[str, str] = {}
for _name in sorted(VARIATIONS_ONLY):
    _NORMALISED_REPORTERS[re.sub(r"[^a-z0-9]", "", _name.lower())] = _name
for _name in sorted(EDITIONS):
    _NORMALISED_REPORTERS[re.sub(r"[^a-z0-9]", "", _name.lower())] = _name


@dataclass
class Suggestion:
    """One proposed replacement, with why it is being proposed."""

    replacement: str
    reason: str


@dataclass
class Finding:
    """Something a reviewer should decide about."""

    kind: str
    text: str
    span: tuple[int, int]
    context: str
    message: str
    suggestions: list[Suggestion] = field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "text": self.text,
            "span": list(self.span),
            "context": self.context,
            "message": self.message,
            "suggestions": [asdict(s) for s in self.suggestions],
        }


def _context(text: str, start: int, end: int, width: int = 60) -> str:
    left = max(0, start - width)
    right = min(len(text), end + width)
    return " ".join(text[left:right].split())


def _edit_distance(a: str, b: str, cap: int = 3) -> int:
    """Levenshtein distance, short-circuited once it exceeds cap."""
    if abs(len(a) - len(b)) > cap:
        return cap + 1
    previous = list(range(len(b) + 1))
    for i, ch_a in enumerate(a, 1):
        current = [i]
        for j, ch_b in enumerate(b, 1):
            current.append(
                min(
                    previous[j] + 1,
                    current[j - 1] + 1,
                    previous[j - 1] + (ch_a != ch_b),
                )
            )
        if min(current) > cap:
            return cap + 1
        previous = current
    return previous[-1]


def _near_reporters(token: str, limit: int = 4) -> list[tuple[str, int]]:
    """Known reporters within a small edit distance of a token."""
    key = re.sub(r"[^a-z0-9]", "", token.lower())
    if not key:
        return []
    scored: list[tuple[str, int]] = []
    for normalised, original in _NORMALISED_REPORTERS.items():
        distance = _edit_distance(key, normalised)
        if distance <= 2:
            scored.append((original, distance))
    scored.sort(key=lambda pair: (pair[1], len(pair[0])))
    return scored[:limit]


def _confusion_candidates(word: str) -> list[tuple[str, str]]:
    """Alternate spellings implied by known OCR confusions."""
    out: list[tuple[str, str]] = []
    seen = {word}
    for seen_seq, likely in _CONFUSIONS:
        if seen_seq not in word:
            continue
        candidate = word.replace(seen_seq, likely, 1)
        if candidate != word and candidate not in seen:
            seen.add(candidate)
            out.append((candidate, f"{seen_seq!r} is commonly a misread {likely!r}"))
    return out


def _covered(spans: list[tuple[int, int]], start: int, end: int) -> bool:
    return any(s <= start and end <= e for s, e in spans)


def find_missed_citations(text: str, extraction: dict) -> list[Finding]:
    """Citation-shaped text that extraction did not pick up."""
    covered: list[tuple[int, int]] = []
    for group in extraction.get("groups", []):
        for cite in (group["header"], *group["children"]):
            covered.append(tuple(cite["span"]))
    for cite in extraction.get("orphans", []):
        covered.append(tuple(cite["span"]))
    for group in extraction.get("authorities", []):
        for cite in (group["header"], *group["children"]):
            covered.append(tuple(cite["span"]))

    findings: list[Finding] = []
    for match in _CITATION_SHAPE.finditer(text):
        start, end = match.span()
        if _covered(covered, start, end):
            continue
        reporter = " ".join(match.group("reporter").split())
        if not reporter or reporter.lower() in {"at", "of", "to", "no", "page"}:
            continue
        # "489 P.3d at 1231" is a short form, and it is normally extracted. The
        # shape regex swallows the "at" into the reporter group, so strip it
        # before deciding whether the reporter is real.
        reporter = re.sub(r"\s+at$", "", reporter, flags=re.IGNORECASE).strip()
        if not reporter:
            continue
        # Rules of procedure and evidence share this shape ("Crim. P. 41") but
        # are not reporters; proposing the nearest reporter to "Crim. P." is
        # nonsense. They are handled by the authorities extractor.
        if _RULE_MARKER.search(reporter):
            continue
        # A reporter is letters and dots, not a word of prose.
        if len(reporter) > 12 or not re.fullmatch(
            r"[A-Za-z][A-Za-z0-9.'’ ]*", reporter
        ):
            continue
        # Every reporter abbreviation carries a period or a digit: "P.3d",
        # "R3d", "U.S.". A bare word does not, and "12 March 2026" was being
        # offered as "12 Marsh. 2026".
        if "." not in reporter and not any(ch.isdigit() for ch in reporter):
            continue
        near = [pair for pair in _near_reporters(reporter) if pair[1] <= 1]
        if not near:
            continue
        if any(distance == 0 for _, distance in near):
            continue  # reporter is real; extraction skipped it for another reason
        findings.append(
            Finding(
                kind="missed_citation",
                text=match.group(0),
                span=(start, end),
                context=_context(text, start, end),
                message=(
                    f"Looks like a citation but was not extracted. "
                    f"{reporter!r} is not a known reporter."
                ),
                suggestions=[
                    Suggestion(
                        replacement=f"{match.group('volume')} {name} {match.group('page')}",
                        reason=f"{name!r} is a known reporter ({distance} character(s) different)",
                    )
                    for name, distance in near
                ],
            )
        )
    return findings


def find_suspect_names(text: str, extraction: dict) -> list[Finding]:
    """Party names containing sequences Tesseract commonly gets wrong.

    A candidate is only offered when that exact spelling appears elsewhere in
    the same document. Without that rule the detector fires on any name holding
    an "li" or an "l" -- "Williamson", "People" -- and the noise makes the whole
    review worthless. The trade is recall: a name misread every single time,
    with the correct spelling never appearing, will not be caught here. That is
    what verification against the reporter is for.
    """
    findings: list[Finding] = []
    seen_words: set[str] = set()

    for group in extraction.get("groups", []):
        # Repeat full citations become children, so the misread spelling is
        # usually NOT the header.
        for header in (group["header"], *group["children"]):
            for role in ("plaintiff", "defendant"):
                name = header.get(role)
                if not name:
                    continue
                for word in name.split():
                    bare = word.strip(".,'’")
                    if len(bare) < 4 or not bare[:1].isupper():
                        continue
                    if bare in seen_words:
                        continue
                    candidates = [
                        (cand, why, len(re.findall(rf"\b{re.escape(cand)}\b", text)))
                        for cand, why in _confusion_candidates(bare)
                    ]
                    # Corroborated by the document itself, or not offered at all.
                    candidates = [c for c in candidates if c[2] > 0]
                    if not candidates:
                        continue
                    candidates.sort(key=lambda c: -c[2])
                    seen_words.add(bare)
                    occurrences = len(re.findall(rf"\b{re.escape(bare)}\b", text))
                    findings.append(
                        Finding(
                            kind="suspect_name",
                            text=bare,
                            span=tuple(header["span"]),
                            context=header.get("full_citation") or header["text"],
                            message=(
                                f"{bare!r} appears {occurrences} time(s) in the {role} "
                                "name and contains a sequence OCR commonly misreads. "
                                "An alternative spelling also appears in this document."
                            ),
                            suggestions=[
                                Suggestion(
                                    replacement=cand,
                                    reason=(
                                        f"{why}; {cand!r} appears {count} time(s) "
                                        "elsewhere in this document"
                                    ),
                                )
                                for cand, why, count in candidates
                            ],
                        )
                    )
    return findings


def find_inconsistent_names(extraction: dict) -> list[Finding]:
    """The same reporter citation carrying more than one party name."""
    by_cite: dict[str, dict[str, int]] = {}
    spans: dict[str, tuple[int, int]] = {}
    for group in extraction.get("groups", []):
        for header in (group["header"], *group["children"]):
            key = " ".join(
                str(header.get(part) or "") for part in ("volume", "reporter", "page")
            ).strip()
            if not key or not header.get("plaintiff"):
                continue
            name = f"{header['plaintiff']} v. {header.get('defendant') or ''}".strip()
            by_cite.setdefault(key, {}).setdefault(name, 0)
            by_cite[key][name] += 1
            spans.setdefault(key, tuple(header["span"]))

    findings: list[Finding] = []
    for key, names in by_cite.items():
        if len(names) < 2:
            continue
        listed = ", ".join(
            f"{n!r} (x{c})" for n, c in sorted(names.items(), key=lambda kv: -kv[1])
        )
        findings.append(
            Finding(
                kind="inconsistent_name",
                text=key,
                span=spans[key],
                context=listed,
                message=(
                    f"{key} appears with {len(names)} different case names. At most "
                    "one can be right. No majority is assumed: on a real opinion the "
                    "misread spelling outnumbered the correct one 11 to 1."
                ),
                suggestions=[
                    Suggestion(replacement=name, reason=f"seen {count} time(s)")
                    for name, count in sorted(names.items(), key=lambda kv: -kv[1])
                ],
            )
        )
    return findings


def review(text: str, extraction: dict) -> list[Finding]:
    """All findings, in document order."""
    findings = (
        find_missed_citations(text, extraction)
        + find_suspect_names(text, extraction)
        + find_inconsistent_names(extraction)
    )
    findings.sort(key=lambda f: f.span[0])
    return findings
